import { NextIntlClientProvider } from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
          <ToastContainer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}